import { Component } from "@angular/core";

@Component({
    selector: "app-carosello-home",
    templateUrl: "./carosello-home.component.html",
    styleUrls: ["./carosello-home.component.css"],
})
export class CaroselloHomeComponent {
    carosello: any = [
        {
            bandiera: "bahrain",
            nazione: "BAHRAIN",
            nome: "Bahrain Grand Prix",
            giorni: "29-02",
            mese: "febb-mar",
        },
        {
            bandiera: "arabia-saudita",
            nazione: "SAUDI ARABIA",
            nome: "Saudi Arabian Grand Prix",
            giorni: "07-09",
            mese: "marzo",
        },
        {
            bandiera: "australia",
            nazione: "AUSTRALIA",
            nome: "Australian Grand Prix",
            giorni: "22-24",
            mese: "marzo",
        },
        {
            bandiera: "giappone",
            nazione: "JAPAN",
            nome: "Japanese Grand Prix",
            giorni: "05-07",
            mese: "aprile",
        },
        {
            bandiera: "cina",
            nazione: "CHINA",
            nome: "Chinese Grand Prix",
            giorni: "19-21",
            mese: "aprile",
        },
        {
            bandiera: "usa",
            nazione: "UNITED STATES",
            nome: "Miami Grand Prix",
            giorni: "03-05",
            mese: "maggio",
        },
        {
            bandiera: "italia",
            nazione: "ITALY",
            nome: "Emilia Romagna Gran Prix",
            giorni: "17-19",
            mese: "maggio",
        },
        {
            bandiera: "monaco",
            nazione: "MONACO",
            nome: "Gran Prix de Monaco",
            giorni: "24-26",
            mese: "maggio",
        },
        {
            bandiera: "canada",
            nazione: "CANADA",
            nome: "Gran Prix du Canada",
            giorni: "07-09",
            mese: "giugno",
        },
        {
            bandiera: "spagna",
            nazione: "SPAIN",
            nome: "Gran Premio de Espana",
            giorni: "21-23",
            mese: "giugno",
        },
        {
            bandiera: "austria",
            nazione: "AUSTRIA",
            nome: "Austrian Grand Prix",
            giorni: "28-30",
            mese: "giugno",
        },
        {
            bandiera: "gran-bretania",
            nazione: "GREAT BRITAIN",
            nome: "British Grand Prix",
            giorni: "05-07",
            mese: "luglio",
        },
        {
            bandiera: "ungheria",
            nazione: "HUNGARY",
            nome: "Hungaria Grand Prix",
            giorni: "19-21",
            mese: "luglio",
        },
        {
            bandiera: "belgio",
            nazione: "BELGIUM",
            nome: "Belgium Grand Prix",
            giorni: "26-28",
            mese: "luglio",
        },
        {
            bandiera: "olanda",
            nazione: "NETHERLANDS",
            nome: "Dutch Grand Prix",
            giorni: "23-25",
            mese: "agosto",
        },
        {
            bandiera: "italia",
            nazione: "ITALY",
            nome: "Gran Premio d'Italia",
            giorni: "30-01",
            mese: "ago-sett",
        },
        {
            bandiera: "azerbaijan",
            nazione: "AZERBAIJAN",
            nome: "Azerbaijan Grand Prix",
            giorni: "13-15",
            mese: "settembre",
        },
        {
            bandiera: "singapore",
            nazione: "SINGAPORE",
            nome: "Singapore Grand Prix",
            giorni: "20-22",
            mese: "settembre",
        },
        {
            bandiera: "usa",
            nazione: "UNITED STATES",
            nome: "United States Grand Prix",
            giorni: "18-20",
            mese: "ottobre",
        },
        {
            bandiera: "messico",
            nazione: "MEXICO",
            nome: "Mexico Grand Prix",
            giorni: "25-27",
            mese: "ottobre",
        },
        {
            bandiera: "brasile",
            nazione: "BRAZIL",
            nome: "Brazilian Grand Prix",
            giorni: "01-03",
            mese: "novembre",
        },
        {
            bandiera: "usa",
            nazione: "UNITED STATES",
            nome: "Las Vegas Grand Prix",
            giorni: "21-23",
            mese: "novembre",
        },
        {
            bandiera: "qatar",
            nazione: "QATAR",
            nome: "Qatar Grand Prix",
            giorni: "29-01",
            mese: "nov-dic",
        },
        {
            bandiera: "abu-dhabi",
            nazione: "ABU-DHABI",
            nome: "Abu Dhabi Grand Prix",
            giorni: "06-08",
            mese: "dicembre",
        },
    ];
}
